AllCops:
  Exclude:
    - "vendor/**/*" # rubocop config/default.yml
    - "db/**/*"
    - 'config/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'lib/tasks/auto_annotate_models.rake'

Metrics/LineLength:
  Exclude:
    - "Rakefile"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false


