version: 2
jobs:
  build:
    working_directory: ~/a-chess/chat-app
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          RAILS_ENV: test
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes

    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - app-{{ checksum "Gemfile.lock" }}
            - app-

      # Bundle install
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle

      # Yarn install  
      - run: yarn

      # Store bundle cache
      - save_cache:
          key: app-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - vendor/bundle
            - node_modules

      # rubocop
      - run: bundle exec rubocop

      # DB wait
      - run: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m

      # Setup the database
      - run: bundle exec rake db:create
      - run: bundle exec rake db:migrate

      # Precompile assets
      - run: bundle exec bin/webpack

      # Run the rspec
      - run: bundle exec rspec --color --fail-fast

      - deploy:
          name: Capistranoデプロイ
          command: |
            if [ "${CIRCLE_BRANCH}" != "master" ]; then
              exit 0
            fi
            
            bundle exec cap production deploy


